Repository Kuama-IT/kerbero, pull requests merged in 2022-12, with the labels that each got.

#154 Create smartlock-key controllers and integration tests
  web-api/src/Kerbero.Domain/Common/Interfaces/InteractorInterface.cs
  web-api/src/Kerbero.Domain/Common/Models/SmartLockProviderModel.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/CreateNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Dtos/CreateSmartLockKeyParams.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Dtos/SmartLockKeyDto.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Entities/SmartLockKey.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CreateSmartLockKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interfaces/ICreateSmartLockKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Managers/ISmartLockKeyGeneratorManager.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Managers/SmartLockKeyGeneratorManager.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Mappers/SmartLockKeyMapper.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Models/PresentationRequests/CreateSmartLockKeyPresentationRequest.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Models/SmartLockKeyModel.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Repositories/ISmartLockKeyPersistentRepository.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Repositories/ISmartLockKeyRepository.cs
  web-api/src/Kerbero.Infrastructure/Common/Context/ApplicationDbContext.cs
  web-api/src/Kerbero.Infrastructure/Common/Interfaces/IApplicationDbContext.cs
  web-api/src/Kerbero.Infrastructure/ConfigureService.cs
  web-api/src/Kerbero.Infrastructure/Migrations/20221130113343_Init.Designer.cs
  web-api/src/Kerbero.Infrastructure/Migrations/20221130113343_Init.cs
  web-api/src/Kerbero.Infrastructure/Migrations/ApplicationDbContextModelSnapshot.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Repositories/NukiCredentialRepository.cs
  web-api/src/Kerbero.Infrastructure/SmartLockKeys/Entities/SmartLockKeyEntity.cs
  web-api/src/Kerbero.Infrastructure/SmartLockKeys/Mappers/SmartLockKeyMapper.cs
  web-api/src/Kerbero.Infrastructure/SmartLockKeys/Repositories/SmartLockKeyRepository.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Models/ENukiSmartLockState.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Repositories/NukiSmartLockRepository.cs
  web-api/src/Kerbero.WebApi/ConfigureService.cs
  web-api/src/Kerbero.WebApi/Controllers/NukiCredentialsController.cs
  web-api/src/Kerbero.WebApi/Controllers/SmartLockKeyController.cs
  web-api/src/Kerbero.WebApi/Models/Requests/CreateNukiCredentialRequest.cs
  web-api/src/Kerbero.WebApi/Models/Requests/CreateSmartLockKeyRequest.cs
  web-api/src/Kerbero.WebApi/Utils/Extensions/ModelStateDictionaryExtension.cs
  web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/GetNukiCredentialInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Managers/SmartLockKeyGeneratorManagerTest.cs
  web-api/tests/Kerbero.Infrastructure.Tests/NukiCredentials/Repositories/NukiCredentialRepositoryTests.cs
  web-api/tests/Kerbero.Infrastructure.Tests/SmartLockKeys/Repositories/SmartLockKeyPersistentRepositoryTests.cs
  web-api/tests/Kerbero.Infrastructure.Tests/SmartLocks/Repositories/NukiSmartLockRepositoryTests.cs
  web-api/tests/Kerbero.Integration.Tests/KerberoWebApplicationFactory.cs
  web-api/tests/Kerbero.Integration.Tests/NukiCredentials/NukiAuthenticationIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/CreateSmartLockKeyIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLocks/SmartLockIntegrationTests.cs
Labels: size/XL

#164 feat(DbContext): add DateTime conversion to always save date on UTC required by postgres
  web-api/src/Kerbero.Infrastructure/Common/Context/ApplicationDbContext.cs
Labels: size/S

#163 feat: drop interactor base interface
  web-api/src/Kerbero.Domain/Common/Interfaces/InteractorInterface.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Dtos/CreateNukiCredentialParams.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Dtos/GetNukiCredentialParams.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Dtos/GetNukiCredentialsByUserInteractorParams.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/CreateNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/GetNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/GetNukiCredentialsByUserInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interfaces/ICreateNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interfaces/IGetNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interfaces/IGetNukiCredentialsByUserInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Dtos/CreateSmartLockKeyParams.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CreateSmartLockKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interfaces/ICreateSmartLockKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Dtos/OpenSmartLockParams.cs
  web-api/src/Kerbero.Domain/SmartLocks/Interactors/GetSmartLocksInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Interactors/OpenSmartLockInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Interfaces/IGetSmartLocksInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Interfaces/IOpenSmartLockInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Params/GetSmartLocksInteractorParams.cs
  web-api/src/Kerbero.WebApi/Controllers/NukiCredentialsController.cs
  web-api/src/Kerbero.WebApi/Controllers/SmartLockKeyController.cs
  web-api/src/Kerbero.WebApi/Controllers/SmartLocksController.cs
  web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/CreateNukiCredentialInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/GetNukiCredentialInteractorTests.cs
Labels: size/L

#166 Random word generator for smart lock key
  web-api/src/Kerbero.Domain/Kerbero.Domain.csproj
  web-api/src/Kerbero.Domain/SmartLockKeys/Dtos/SmartLockKeyDto.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Mappers/SmartLockKeyMapper.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Models/SmartLockKeyModel.cs
  web-api/src/Kerbero.Infrastructure/Migrations/ApplicationDbContextModelSnapshot.cs
  web-api/src/Kerbero.Infrastructure/SmartLockKeys/Entities/SmartLockKeyEntity.cs
  web-api/src/Kerbero.Infrastructure/SmartLockKeys/Mappers/SmartLockKeyMapper.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/GetSmartLockKeysInteractorTests.cs
  web-api/tests/Kerbero.Infrastructure.Tests/SmartLockKeys/Repositories/SmartLockKeyRepositoryTests.cs
  web-api/tests/Kerbero.Integration.Tests/IntegrationTestsUtils.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/GetSmartLockKeysIntegrationTests.cs
Labels: size/M

#165 Open smart lock with smartlock key interactor (needs migrations)
  web-api/src/Kerbero.Domain/NukiCredentials/Models/NukiCredentialModel.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Dtos/SmartLockKeyDto.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Errors/SmartLockKeyExpiredError.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CreateSmartLockKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/OpenSmartLockWithKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interfaces/IOpenSmartLockWithKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Mappers/SmartLockKeyMapper.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Models/SmartLockKeyModel.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Repositories/ISmartLockKeyRepository.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Mappers/NukiCredentialMapper.cs
  web-api/src/Kerbero.Infrastructure/SmartLockKeys/Entities/SmartLockKeyEntity.cs
  web-api/src/Kerbero.Infrastructure/SmartLockKeys/Mappers/SmartLockKeyMapper.cs
  web-api/src/Kerbero.Infrastructure/SmartLockKeys/Repositories/SmartLockKeyRepository.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Mappers/SmartLockMapper.cs
  web-api/src/Kerbero.WebApi/Models/Requests/OpenSmartLockWithKeyRequest.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/GetSmartLockKeysInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/OpenSmartLockWithKeyInteractorTests.cs
  web-api/tests/Kerbero.Infrastructure.Tests/SmartLockKeys/Repositories/SmartLockKeyRepositoryTests.cs
  web-api/tests/Kerbero.Integration.Tests/IntegrationTestsUtils.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/GetSmartLockKeysIntegrationTests.cs
Labels: size/L

#174 feat: build nuki redirect uri interactor
  web-api/src/Kerbero.Domain/Common/Repositories/IKerberoConfigurationRepository.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/BuildNukiRedirectUriInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interfaces/IBuildNukiRedirectUriInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Models/NukiApiConfigurationModel.cs
  web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/BuildNukiRedirectUriTests.cs
Labels: size/L

#175 feat: create nuki draft credential interactor
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/CreateNukiCredentialDraftInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interfaces/ICreateNukiCredentialDraftInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Models/NukiCredentialDraftModel.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Repositories/INukiCredentialRepository.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Repositories/NukiCredentialRepository.cs
  web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/BuildNukiRedirectUriInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/CreateNukiCredentialDraftInteractorTests.cs
Labels: size/L

#176 feat: confirm nuki draft credential interactor
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/ConfirmNukiDraftCredentialsInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interfaces/IConfirmNukiDraftCredentialsInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Models/NukiRefreshableCredentialModel.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Repositories/INukiCredentialRepository.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Repositories/NukiCredentialRepository.cs
  web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/ConfirmNukiDraftCredentialsInteractorTests.cs
Labels: size/L

#177 chore: give more explicit name to refresh nuki auth token method
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/CreateNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Repositories/INukiCredentialRepository.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Repositories/NukiCredentialRepository.cs
  web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/CreateNukiCredentialInteractorTests.cs
Labels: size/S

#178 feat: kerbero configuration repository
  web-api/src/Kerbero.Infrastructure/Common/Repositories/KerberoConfigurationRepository.cs
Labels: size/S

#179 feat: allow refresh token on nuki credential
  web-api/src/Kerbero.Infrastructure/Migrations/20221203125413_Init.Designer.cs
  web-api/src/Kerbero.Infrastructure/Migrations/20221203125413_Init.cs
  web-api/src/Kerbero.Infrastructure/Migrations/ApplicationDbContextModelSnapshot.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Entities/NukiCredentialEntity.cs
Labels: size/M

#180 feat: implement nuki credential repository (draft credential part)
  web-api/src/Kerbero.Infrastructure/Common/Helpers/NukiSafeHttpCallHelper.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Dtos/NukiOAuthResponseDto.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Mappers/NukiCredentialMapper.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Repositories/NukiCredentialRepository.cs
Labels: size/L

#181 feat: nuki credential draft rest api
  web-api/src/Kerbero.Identity/Extensions/DependencyInjection/ServiceCollectionExtensions.cs
  web-api/src/Kerbero.Infrastructure/Common/Helpers/NukiSafeHttpCallHelper.cs
  web-api/src/Kerbero.Infrastructure/ConfigureService.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Mappers/NukiCredentialMapper.cs
  web-api/src/Kerbero.WebApi/.env-example
  web-api/src/Kerbero.WebApi/ConfigureService.cs
  web-api/src/Kerbero.WebApi/Controllers/NukiCredentialsController.cs
  web-api/src/Kerbero.WebApi/Dtos/NukiCredentialDraftDto.cs
  web-api/src/Kerbero.WebApi/Mappers/NukiCredentialMapper.cs
  web-api/src/Kerbero.WebApi/Properties/launchSettings.json
Labels: size/L

#170 Clean up code from NukiActions (old)
  web-api/src/Kerbero.Domain/NukiActions/Errors/SmartLockNotReachableError.cs
  web-api/src/Kerbero.Domain/NukiActions/Models/ExternalRequests/NukiSmartLockExternalRequest.cs
  web-api/src/Kerbero.Domain/NukiActions/Models/ExternalResponses/NukiSmartLockExternalResponse.cs
  web-api/src/Kerbero.Domain/NukiActions/Models/ExternalResponses/NukiSmartLockStateExternalResponse.cs
  web-api/src/Kerbero.Domain/NukiActions/Models/PresentationRequest/CloseNukiSmartLockPresentationRequest.cs
  web-api/src/Kerbero.Domain/NukiActions/Models/PresentationRequest/CreateNukiSmartLockPresentationRequest.cs
  web-api/src/Kerbero.Domain/NukiActions/Models/PresentationRequest/NukiSmartLocksPresentationRequest.cs
  web-api/src/Kerbero.Domain/NukiActions/Models/PresentationResponse/KerberoSmartLockPresentationResponse.cs
  web-api/src/Kerbero.Domain/NukiActions/Repositories/INukiSmartLockExternalRepository.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interfaces/ICreateSmartLockKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Interactors/OpenSmartLockInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Interfaces/IOpenSmartLockInteractor.cs
  web-api/src/Kerbero.Infrastructure/ConfigureService.cs
  web-api/src/Kerbero.Infrastructure/NukiActions/Repositories/NukiSmartLockExternalRepository.cs
  web-api/src/Kerbero.Infrastructure/SmartLockKeys/Mappers/SmartLockKeyMapper.cs
  web-api/src/Kerbero.WebApi/Controllers/SmartLocksController.cs
  web-api/src/Kerbero.WebApi/Models/Requests/CreateSmartLockKeyRequest.cs
  web-api/src/Kerbero.WebApi/Utils/Extensions/ModelStateDictionaryExtension.cs
  web-api/tests/Kerbero.Infrastructure.Tests/NukiActions/Repositories/NukiSmartLockExternalRepositoryTests.cs
  web-api/tests/Kerbero.Integration.Tests/KerberoWebApplicationFactory.cs
Labels: size/L

#183 Repo and controller for closing smartlock by smartlock id (only nuki supported)
  web-api/src/Kerbero.Infrastructure/SmartLocks/Repositories/NukiSmartLockRepository.cs
  web-api/src/Kerbero.WebApi/ConfigureService.cs
  web-api/src/Kerbero.WebApi/Controllers/SmartLocksController.cs
Labels: size/M

#182 Close smart-lock with key interactor
  web-api/src/Kerbero.Domain/NukiCredentials/Dtos/NukiCredentialDto.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Models/NukiCredentialModel.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CloseSmartLockWithKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interfaces/ICloseSmartLockWithKeyInteractor.cs
  web-api/src/Kerbero.WebApi/Models/Requests/CloseSmartLockWithKeyRequest.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/CloseSmartLockWithKeyInteractorTests.cs
Labels: size/L

#184 chore: adhere to clean architecture rules (no dto in domain)
  web-api/src/Kerbero.Domain/NukiCredentials/Dtos/NukiCredentialDto.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/CreateNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/GetNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/GetNukiCredentialsByUserInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interfaces/ICreateNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interfaces/IGetNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interfaces/IGetNukiCredentialsByUserInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Mappers/NukiCredentialMapper.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CreateSmartLockKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/GetSmartLockKeysInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interfaces/ICreateSmartLockKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interfaces/IGetSmartLockKeysInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Interactors/CloseSmartLockInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Interactors/GetSmartLocksInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Interactors/OpenSmartLockInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Interfaces/IGetSmartLocksInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Mappers/SmartLockMapper.cs
  web-api/src/Kerbero.Domain/SmartLocks/Models/SmartLockModel.cs
  web-api/src/Kerbero.Domain/SmartLocks/Models/SmartLockWithCredentialModel.cs
  web-api/src/Kerbero.Domain/SmartLocks/Repositories/INukiSmartLockRepository.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Mappers/SmartLockMapper.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Repositories/NukiSmartLockRepository.cs
  web-api/src/Kerbero.WebApi/Controllers/NukiCredentialsController.cs
  web-api/src/Kerbero.WebApi/Controllers/SmartLockKeysController.cs
  web-api/src/Kerbero.WebApi/Controllers/SmartLocksController.cs
  web-api/src/Kerbero.WebApi/Dtos/CloseSmartLockRequest.cs
  web-api/src/Kerbero.WebApi/Dtos/CreateNukiCredentialRequestDto.cs
  web-api/src/Kerbero.WebApi/Dtos/CreateSmartLockKeyRequestDto.cs
  web-api/src/Kerbero.WebApi/Dtos/NukiCredentialDraftDto.cs
  web-api/src/Kerbero.WebApi/Dtos/NukiCredentialDraftResponseDto.cs
  web-api/src/Kerbero.WebApi/Dtos/NukiCredentialResponseDto.cs
  web-api/src/Kerbero.WebApi/Dtos/OpenSmartLockRequestDto.cs
  web-api/src/Kerbero.WebApi/Dtos/OpenSmartLockWithKeyRequestDto.cs
  web-api/src/Kerbero.WebApi/Dtos/SmartLockKeyResponseDto.cs
  web-api/src/Kerbero.WebApi/Dtos/SmartLockResponseDto.cs
  web-api/src/Kerbero.WebApi/Dtos/SmartLockStateDto.cs
  web-api/src/Kerbero.WebApi/Mappers/NukiCredentialMapper.cs
  web-api/src/Kerbero.WebApi/Mappers/SmartLockKeyMapper.cs
  web-api/src/Kerbero.WebApi/Mappers/SmartLockMapper.cs
  web-api/src/Kerbero.WebApi/Models/Requests/CreateNukiCredentialRequest.cs
  web-api/src/Kerbero.WebApi/Models/Requests/CreateSmartLockKeyRequest.cs
  web-api/src/Kerbero.WebApi/Models/Requests/OpenSmartLockRequest.cs
  web-api/src/Kerbero.WebApi/Models/Requests/OpenSmartLockWithKeyRequest.cs
  web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/CreateNukiCredentialInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/GetSmartLockKeysInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLocks/Interactors/CloseSmartLockInteractorTests.cs
  web-api/tests/Kerbero.Infrastructure.Tests/SmartLocks/Repositories/NukiSmartLockRepositoryTests.cs
  web-api/tests/Kerbero.Integration.Tests/NukiCredentials/NukiAuthenticationIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/CreateSmartLockKeyIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/GetSmartLockKeysIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/OpenSmartLockWithKeyIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLocks/SmartLockIntegrationTests.cs
Labels: size/L

#194 feat: add email to nuki credentials and date range to smart lock key
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/CreateNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Models/NukiCredentialModel.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CloseSmartLockWithKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CreateSmartLockKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/OpenSmartLockWithKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interfaces/ICreateSmartLockKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Models/SmartLockKeyModel.cs
  web-api/src/Kerbero.Infrastructure/Migrations/20221205115224_Init.Designer.cs
  web-api/src/Kerbero.Infrastructure/Migrations/20221205115224_Init.cs
  web-api/src/Kerbero.Infrastructure/Migrations/ApplicationDbContextModelSnapshot.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Entities/NukiCredentialEntity.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Mappers/NukiCredentialMapper.cs
  web-api/src/Kerbero.Infrastructure/SmartLockKeys/Entities/SmartLockKeyEntity.cs
  web-api/src/Kerbero.Infrastructure/SmartLockKeys/Mappers/SmartLockKeyMapper.cs
  web-api/src/Kerbero.WebApi/Controllers/SmartLockKeysController.cs
  web-api/src/Kerbero.WebApi/Dtos/CreateSmartLockKeyRequestDto.cs
  web-api/src/Kerbero.WebApi/Dtos/SmartLockKeyResponseDto.cs
  web-api/src/Kerbero.WebApi/Mappers/SmartLockKeyMapper.cs
  web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/ConfirmNukiDraftCredentialsInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/CreateNukiCredentialInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/CloseSmartLockWithKeyInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/GetSmartLockKeysInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/OpenSmartLockWithKeyInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLocks/Interactors/CloseSmartLockInteractorTests.cs
  web-api/tests/Kerbero.Infrastructure.Tests/NukiCredentials/Repositories/NukiCredentialRepositoryTests.cs
  web-api/tests/Kerbero.Infrastructure.Tests/SmartLockKeys/Repositories/SmartLockKeyRepositoryTests.cs
  web-api/tests/Kerbero.Infrastructure.Tests/SmartLocks/Repositories/NukiSmartLockRepositoryTests.cs
  web-api/tests/Kerbero.Integration.Tests/IntegrationTestsUtils.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/CreateSmartLockKeyIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/DeleteSmartLockKeyIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/GetSmartLockKeysIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLocks/SmartLockIntegrationTests.cs
Labels: Extra Large

#196 fix: user navigation prop type
  web-api/src/Kerbero.Infrastructure/Migrations/20221205120419_Init.Designer.cs
  web-api/src/Kerbero.Infrastructure/Migrations/20221205120419_Init.cs
  web-api/src/Kerbero.Infrastructure/Migrations/ApplicationDbContextModelSnapshot.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Entities/NukiCredentialEntity.cs
Labels: Small

#195 Get all nuki credentials associated with the kerbero account
  web-api/src/Kerbero.WebApi/Controllers/NukiCredentialsController.cs
  web-api/src/Kerbero.WebApi/Mappers/NukiCredentialMapper.cs
Labels: Extra Small

#197 feat: validate keys based on date range
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CloseSmartLockWithKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/OpenSmartLockWithKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Models/SmartLockKeyModel.cs
  web-api/src/Kerbero.WebApi/Utils/Extensions/ModelStateDictionaryExtension.cs
  web-api/tests/Kerbero.Integration.Tests/IntegrationTestsUtils.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/OpenSmartLockWithKeyIntegrationTests.cs
Labels: Large

#199 Delete credentials by id (only for nuki)
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/DeleteNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interfaces/IDeleteNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Repositories/INukiCredentialRepository.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Repositories/NukiCredentialRepository.cs
  web-api/src/Kerbero.WebApi/ConfigureService.cs
  web-api/src/Kerbero.WebApi/Controllers/NukiCredentialsController.cs
  web-api/tests/Kerbero.Integration.Tests/NukiCredentials/NukiAuthenticationIntegrationTests.cs
Labels: Small

#200 feat: fetch nuki account email and store it inside our credentials
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/CreateNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Repositories/INukiCredentialRepository.cs
  web-api/src/Kerbero.Infrastructure/Common/Helpers/NukiRestApiClient.cs
  web-api/src/Kerbero.Infrastructure/Common/Helpers/NukiSafeHttpCallHelper.cs
  web-api/src/Kerbero.Infrastructure/ConfigureService.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Dtos/NukiAccountResponseDto.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Repositories/NukiCredentialRepository.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Repositories/NukiSmartLockRepository.cs
  web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/CreateNukiCredentialInteractorTests.cs
  web-api/tests/Kerbero.Infrastructure.Tests/NukiCredentials/Repositories/NukiCredentialRepositoryTests.cs
  web-api/tests/Kerbero.Infrastructure.Tests/SmartLocks/Repositories/NukiSmartLockRepositoryTests.cs
  web-api/tests/Kerbero.Integration.Tests/NukiCredentials/NukiAuthenticationIntegrationTests.cs
Labels: Large

#203 Moved apiToken nullability check to repository
  web-api/src/Kerbero.Infrastructure/Common/Helpers/NukiRestApiClient.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Repositories/NukiSmartLockRepository.cs
  web-api/tests/Kerbero.Infrastructure.Tests/SmartLocks/Repositories/NukiSmartLockRepositoryTests.cs
Labels: Extra Small

#204 Allow to update valid date range for smart lock keys
  web-api/Kerbero.sln
  web-api/src/Kerbero.Domain/SmartLockKeys/Errors/SmartLockKeyPastValidFromError.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Errors/SmartLockKeyValidUntilPrecedeValidFromError.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CreateSmartLockKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/UpdateSmartLockKeyValidityInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interfaces/IUpdateSmartLockKeyValidityInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Models/SmartLockKeyModel.cs
  web-api/src/Kerbero.WebApi/ConfigureService.cs
  web-api/src/Kerbero.WebApi/Controllers/SmartLockKeysController.cs
  web-api/src/Kerbero.WebApi/Dtos/SmartLockKeys/UpdateSmartLockKeyRequestDto.cs
  web-api/src/Kerbero.WebApi/Utils/Extensions/ModelStateDictionaryExtension.cs
  web-api/tests/Kerbero.Integration.Tests/Kerbero.Integration.Tests.csproj
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/UpdateSmartLockKeyValidityIntegrationTests.cs
Labels: Medium

#207 feat: manage refreshable credentials
  web-api/src/Kerbero.Data/Common/Helpers/NukiRestApiClient.cs
  web-api/src/Kerbero.Data/NukiCredentials/Mappers/NukiCredentialMapper.cs
  web-api/src/Kerbero.Data/NukiCredentials/Repositories/NukiCredentialRepository.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/DeleteNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/EnsureNukiCredentialBelongsToUserInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/GetNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/GetNukiCredentialsByUserInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interfaces/IEnsureNukiCredentialBelongsToUserInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interfaces/IGetNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interfaces/IGetNukiCredentialsByUserInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Models/NukiCredentialModel.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Models/UserNukiCredentialsModel.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Repositories/INukiCredentialRepository.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CloseSmartLockWithKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CreateSmartLockKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/DeleteSmartLockKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/GetSmartLockKeysInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/OpenSmartLockWithKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/UpdateSmartLockKeyValidityInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interfaces/IGetSmartLockKeysInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Models/UserSmartLockKeysModel.cs
  web-api/src/Kerbero.Domain/SmartLocks/Interactors/CloseSmartLockInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Interactors/OpenSmartLockInteractor.cs
  web-api/src/Kerbero.WebApi/ConfigureService.cs
  web-api/src/Kerbero.WebApi/Controllers/NukiCredentialsController.cs
  web-api/src/Kerbero.WebApi/Controllers/SmartLockKeysController.cs
  web-api/src/Kerbero.WebApi/Controllers/SmartLocksController.cs
  web-api/src/Kerbero.WebApi/Dtos/NukiCredentials/NukiCredentialListResponseDto.cs
  web-api/src/Kerbero.WebApi/Dtos/NukiCredentials/OutdatedNukiCredentialResponseDto.cs
  web-api/src/Kerbero.WebApi/Dtos/SmartLockKeys/SmartLockKeyListResponseDto.cs
  web-api/src/Kerbero.WebApi/Dtos/SmartLocks/SmartLockListResponseDto.cs
  web-api/src/Kerbero.WebApi/Mappers/NukiCredentialMapper.cs
  web-api/src/Kerbero.WebApi/Mappers/SmartLockKeyMapper.cs
  web-api/src/Kerbero.WebApi/Mappers/SmartLockMapper.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/CloseSmartLockWithKeyInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/GetSmartLockKeysInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/OpenSmartLockWithKeyInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLocks/Interactors/CloseSmartLockInteractorTests.cs
  web-api/tests/Kerbero.Integration.Tests/NukiCredentials/NukiAuthenticationIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/DeleteSmartLockKeyIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/GetSmartLockKeysIntegrationTests.cs
Labels: Extra Large

#208 Fix integration test application initialization
  web-api/tests/Kerbero.Integration.Tests/KerberoWebApplicationFactory.cs
  web-api/tests/Kerbero.Integration.Tests/NukiCredentials/NukiAuthenticationIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/CloseSmartLockWithKeyIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/CreateSmartLockKeyIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/DeleteSmartLockKeyIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/GetSmartLockKeysIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/OpenSmartLockWithKeyIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLockKeys/UpdateSmartLockKeyValidityIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLocks/SmartLockIntegrationTests.cs
Labels: Extra Small

#217 list/open/close smart-lock api calls
  web-app/src/smart-locks/api/smart-lock-actions.ts
  web-app/src/smart-locks/api/smart-lock.schemas.ts
  web-app/test/smartlock-keys/api/smart-lock-actions.test.ts
Labels: Medium

#218 Create/delete nuki-credential api calls
  web-app/src/nuki-credentials/api/nuki-credential-actions.ts
  web-app/src/nuki-credentials/api/nuki-credential.schemas.ts
  web-app/src/shared/http-client/http-client.ts
Labels: Extra Small

#219 Open/close/update/delete smart-lock-key api calls
  web-app/src/smart-lock-keys/api/smart-lock-key-actions.ts
  web-app/src/smart-lock-keys/api/smart-lock-key.schemas.ts
Labels: Small

#121 Sign up component
  .github/workflows/webapp-integration.yml
  web-api/src/Kerbero.WebApi/Program.cs
  web-app/.eslintrc.cjs
  web-app/cypress.config.ts
  web-app/cypress/support/auth-routing.cy.ts
  web-app/package-lock.json
  web-app/package.json
  web-app/src/auth/api/auth-actions.ts
  web-app/src/auth/components/log-in.component.vue
  web-app/src/auth/components/sign-in.component.vue
  web-app/src/auth/components/sign-up.component.vue
  web-app/src/auth/pages/authenticate-page.component.vue
  web-app/src/main.ts
  web-app/src/shared/http-client/http-client.ts
  web-app/test/auth/api/auth-sign-in.api.test.ts
  web-app/test/auth/api/auth-sign-up.api.test.ts
  web-app/test/auth/stores/auth.store.test.ts
  web-app/vite.config.ts
Labels: size/L, Large

#225 fix: user store update and redirect to dashboard after login
  web-app/src/auth/components/sign-in.component.vue
  web-app/src/routing/routing-guards.ts
Labels: Extra Small

#223 Smart-lock list item component
  web-app/src/shared/icons/doors-icon.component.vue
  web-app/src/smart-locks/components/smart-lock-list-item.component.vue
  web-app/tailwind.config.cjs
Labels: Small

#227 Smart lock list component
  web-app/src/smart-locks/api/smart-lock.schemas.ts
  web-app/src/smart-locks/components/smart-lock-list-item.component.vue
  web-app/src/smart-locks/components/smart-lock-list.component.vue
Labels: Extra Small

#228 User credential list item component
  web-app/package-lock.json
  web-app/package.json
  web-app/src/smart-lock-keys/api/smart-lock-key.schemas.ts
  web-app/src/smart-locks/api/smart-lock.schemas.ts
  web-app/src/user-credentials/api/nuki-credential-actions.ts
  web-app/src/user-credentials/api/nuki-credential.schemas.ts
  web-app/src/user-credentials/components/credential-item.component.vue
  web-app/tsconfig.json
Labels: Extra Small

#229 Add credential button component
  web-app/src/shared/components/create-new-one-button.component.vue
Labels: Extra Small

#231 Font update and authentication update
  web-app/src/auth/components/sign-in.component.vue
  web-app/src/auth/components/sign-up.component.vue
  web-app/src/auth/pages/authenticate-page.component.vue
  web-app/src/styles.scss
Labels: Extra Small

#230 feat: datetime-widget-component
  web-app/src/shared/components/datetime-widget.component.vue
Labels: Extra Small

#233 Typescript import and alias fix
  web-app/tsconfig.json
Labels: Extra Small

#232 Datetime component with picker and display for smart-lock-key
  web-app/package-lock.json
  web-app/package.json
  web-app/src/shared/components/datetime-widget.component.vue
  web-app/src/shared/utils/date-time-formatter.ts
  web-app/src/smart-lock-keys/components/date-time-display.component.vue
  web-app/src/smart-lock-keys/components/date-time-manager.component.vue
  web-app/src/smart-lock-keys/components/date-time-picker.component.vue
Labels: Medium

#234 Smart lock key component
  web-app/src/smart-lock-keys/api/smart-lock-key.schemas.ts
  web-app/src/smart-lock-keys/components/date-time-display.component.vue
  web-app/src/smart-lock-keys/components/date-time-manager.component.vue
  web-app/src/smart-lock-keys/components/date-time-picker.component.vue
  web-app/src/smart-lock-keys/components/smart-lock-keys-item.component.vue
Labels: Small

#236 Improved and fixed oauth authentication to nuki web apis
  web-api/src/Kerbero.Data/Common/Repositories/KerberoConfigurationRepository.cs
  web-api/src/Kerbero.Data/Migrations/20221214145728_Init.Designer.cs
  web-api/src/Kerbero.Data/Migrations/20221214145728_Init.cs
  web-api/src/Kerbero.Data/Migrations/ApplicationDbContextModelSnapshot.cs
  web-api/src/Kerbero.Data/NukiCredentials/Entities/NukiCredentialEntity.cs
  web-api/src/Kerbero.Data/NukiCredentials/Mappers/NukiCredentialMapper.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/BuildNukiRedirectUriInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/BuildWebAppRedirectUriInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/ConfirmNukiDraftCredentialsInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interfaces/IBuildWebAppRedirectUriInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Models/NukiApiConfigurationModel.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Utils/BuildRedirectToKerberoUriHelper.cs
  web-api/src/Kerbero.WebApi/.env-example
  web-api/src/Kerbero.WebApi/ConfigureService.cs
  web-api/src/Kerbero.WebApi/Controllers/NukiCredentialsController.cs
  web-api/src/Kerbero.WebApi/Program.cs
  web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/BuildNukiRedirectUriInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/ConfirmNukiDraftCredentialsInteractorTests.cs
Labels: Small

#235 Smart lock keys list component
  web-app/src/smart-lock-keys/components/date-time-manager.component.vue
  web-app/src/smart-lock-keys/components/smart-lock-keys-item.component.vue
  web-app/src/smart-lock-keys/components/smart-lock-keys-list.component.vue
Labels: Extra Small

#237 Create "create provider page"
  web-app/src/dashboard/pages/dashboard-page.component.vue
  web-app/src/routing/router.ts
  web-app/src/user-credentials/api/nuki-credential-actions.ts
  web-app/src/user-credentials/components/select-provider.component.vue
  web-app/src/user-credentials/pages/create-new-provider.page.vue
  web-app/vite.config.ts
Labels: Small

#238 Logo icon svg
  web-app/index.html
  web-app/public/logo.svg
Labels: Extra Small

#239 User info component
  web-app/src/assets/img.png
  web-app/src/user-credentials/components/user-stats.component.vue
  web-app/tailwind.config.cjs
Labels: Extra Small

#241 feat: /smart-locks page
  web-app/src/routing/router.ts
  web-app/src/shared/components/sync-loader.component.vue
  web-app/src/smart-locks/api/smart-lock-actions.ts
  web-app/src/smart-locks/components/smart-lock-list-item.component.vue
  web-app/src/smart-locks/components/smart-lock-list.component.vue
  web-app/src/smart-locks/pages/smart-locks.page.vue
  web-app/vitest.config.ts
Labels: Medium
