Repository Kuama-IT/kerbero, pull requests merged in 2022-11, with the labels that each got.

#36 feat: external repository to open smartlock
  src/Kerbero.Infrastructure/Common/Helpers/NukiSafeHttpCallHelper.cs
  src/Kerbero.Infrastructure/NukiActions/Repositories/NukiSmartLockExternalRepository.cs
  tests/Kerbero.Infrastructure.Tests/NukiActions/Repositories/NukiSmartLockExternalRepositoryTests.cs
Labels: size/M

#37 feat: controller to create nuki smartlock
  src/Kerbero.Domain/NukiActions/Interactors/CreateNukiSmartLockInteractor.cs
  src/Kerbero.Domain/NukiActions/Interactors/GetNukiSmartLocksInteractor.cs
  src/Kerbero.Domain/NukiActions/Mappers/NukiSmartLockMapper.cs
  src/Kerbero.Domain/NukiActions/Models/Mapper/NukiSmartLockMapper.cs
  src/Kerbero.Domain/NukiActions/Models/PresentationRequest/CreateNukiSmartLockPresentationRequest.cs
  src/Kerbero.Infrastructure/ConfigureService.cs
  src/Kerbero.WebApi/ConfigureService.cs
  src/Kerbero.WebApi/Controllers/NukiSmartLockController.cs
  tests/Kerbero.Domain.Tests/NukiActions/Interactors/CreateNukiSmartLockInteractorTest.cs
  tests/Kerbero.WebApi.Tests/NukiSmartLockControllerTests.cs
Labels: size/L

#38 feat: migration to create a smartlock
  src/Kerbero.Domain/NukiActions/Entities/NukiSmartLock.cs
  src/Kerbero.Infrastructure/Common/Migrations/20220929105216_InitialCreate.Designer.cs
  src/Kerbero.Infrastructure/Common/Migrations/20220929105216_InitialCreate.cs
  src/Kerbero.Infrastructure/Common/Migrations/ApplicationDbContextModelSnapshot.cs
  src/Kerbero.Infrastructure/ConfigureService.cs
  src/Kerbero.Infrastructure/Migrations/20221103131158_InitialCreate.Designer.cs
  src/Kerbero.Infrastructure/Migrations/20221103131158_InitialCreate.cs
  src/Kerbero.Infrastructure/Migrations/ApplicationDbContextModelSnapshot.cs
  src/Kerbero.Infrastructure/NukiAuthentication/Configurations/NukiAccountTypeConfiguration.cs
Labels: size/XL

#35 feat: persistent open smartlock
  src/Kerbero.Domain/NukiActions/Interactors/CloseNukiSmartLockInteractor.cs
  src/Kerbero.Domain/NukiActions/Interactors/OpenNukiSmartLockInteractor.cs
  src/Kerbero.Domain/NukiActions/Repositories/INukiSmartLockPersistentRepository.cs
  src/Kerbero.Infrastructure/NukiActions/Repositories/NukiSmartLockPersistentRepository.cs
  src/Kerbero.Infrastructure/NukiAuthentication/Repositories/NukiAccountPersistentRepository.cs
  tests/Kerbero.Domain.Tests/Interactors/NukiActions/OpenNukiSmartLockInteractorTests.cs
  tests/Kerbero.Domain.Tests/NukiActions/Interactors/CloseNukiSmartLockInteractorTest.cs
  tests/Kerbero.Infrastructure.Tests/NukiActions/Repositories/NukiSmartLockPersistentRepositoryTests.cs
Labels: size/L

#49 feat: external repository to close smartlock
  src/Kerbero.Infrastructure/NukiActions/Repositories/NukiSmartLockExternalRepository.cs
  tests/Kerbero.Infrastructure.Tests/NukiActions/Repositories/NukiSmartLockExternalRepositoryTests.cs
Labels: size/M

#45 feat: integration test for creating nuki smartlock
  src/Kerbero.Domain/NukiActions/Mappers/NukiSmartLockMapper.cs
  src/Kerbero.Domain/NukiActions/Models/PresentationResponse/KerberoSmartLockPresentationResponse.cs
  src/Kerbero.Domain/NukiAuthentication/Interactors/AuthenticateNukiAccountInteractor.cs
  src/Kerbero.Infrastructure/NukiAuthentication/Repositories/NukiAccountPersistentRepository.cs
  tests/Kerbero.Domain.Tests/NukiActions/Interactors/GetNukiSmartLocksListInteractorTest.cs
  tests/Kerbero.Domain.Tests/NukiAuthentication/Interactors/GetNukiAccountInteractorTests.cs
  tests/Kerbero.Infrastructure.Tests/NukiAuthentication/Repositories/NukiAccountPersistentRepositoryTest.cs
  tests/Kerbero.Integration.Tests/NukiCreateSmartLockIntegrationTests.cs
  tests/Kerbero.Integration.Tests/NukiSmartLocksListIntegrationTests.cs
  tests/Kerbero.WebApi.Tests/ModelStateDictionaryExtensionsTest.cs
  tests/Kerbero.WebApi.Tests/NukiSmartLockControllerTests.cs
Labels: size/L

#47 feat: controller to open smartlock
  src/Kerbero.Domain/NukiActions/Errors/SmartLockNotReachableError.cs
  src/Kerbero.Infrastructure/ConfigureService.cs
  src/Kerbero.WebApi/ConfigureService.cs
  src/Kerbero.WebApi/Controllers/NukiSmartLockController.cs
  src/Kerbero.WebApi/Utils/Extensions/ModelStateDictionaryExtension.cs
  tests/Kerbero.WebApi.Tests/NukiSmartLockControllerTests.cs
Labels: size/L

#43 feat: update README.md
  README.md
Labels: size/S

#52 feat: controller to close smartlock
  src/Kerbero.WebApi/ConfigureService.cs
  src/Kerbero.WebApi/Controllers/NukiSmartLockController.cs
  tests/Kerbero.Integration.Tests/NukiCreateSmartLockIntegrationTests.cs
  tests/Kerbero.WebApi.Tests/NukiSmartLockControllerTests.cs
Labels: size/M

#75 Migrations for identity
  src/Kerbero.Infrastructure/Migrations/20221110093033_InitialCreate.Designer.cs
  src/Kerbero.Infrastructure/Migrations/20221110093033_InitialCreate.cs
  src/Kerbero.Infrastructure/Migrations/ApplicationDbContextModelSnapshot.cs
Labels: size/L

#77 FindAsync in NukiAccountPersistentRepository.cs
  src/Kerbero.Domain/NukiAuthentication/Errors/NukiAccountNotFoundError.cs
  src/Kerbero.Domain/NukiAuthentication/Interactors/AuthenticateNukiAccountInteractor.cs
  src/Kerbero.Domain/NukiAuthentication/Repositories/INukiAccountPersistentRepository.cs
  src/Kerbero.Infrastructure/NukiAuthentication/Repositories/NukiAccountPersistentRepository.cs
  tests/Kerbero.Domain.Tests/NukiAuthentication/Interactors/GetNukiAccountInteractorTests.cs
  tests/Kerbero.Infrastructure.Tests/NukiAuthentication/Repositories/NukiAccountPersistentRepositoryTest.cs
Labels: size/M

#62 Integration test for opening and closing a smartlock and minor fix
  src/Kerbero.WebApi/Controllers/NukiSmartLockController.cs
  src/Kerbero.WebApi/Models/Requests/CloseNukiSmartLockRequest.cs
  src/Kerbero.WebApi/Models/Requests/CreateNukiSmartLockRequest.cs
  src/Kerbero.WebApi/Models/Requests/OpenNukiSmartLockRequest.cs
  tests/Kerbero.Integration.Tests/NukiCloseSmartLockIntegrationTests.cs
  tests/Kerbero.Integration.Tests/NukiCreateSmartLockIntegrationTests.cs
  tests/Kerbero.Integration.Tests/NukiOpenSmartLockIntegrationTests.cs
  tests/Kerbero.Integration.Tests/NukiSmartLocksListIntegrationTests.cs
  tests/Kerbero.WebApi.Tests/NukiSmartLockControllerTests.cs
Labels: size/M

#82 fix: give scripts execution permissions and update docker folder name
  dev-deploy-script.sh
  kerbero-setup.sh
Labels: size/XS

#89 feat: empty web-app project
  .github/workflows/pr-integration.yml
  .prettierrc.json
  web-app/.eslintignore
  web-app/.eslintrc.cjs
  web-app/.gitignore
  web-app/.husky/pre-commit
  web-app/.vscode/extensions.json
  web-app/README.md
  web-app/cypress.config.ts
  web-app/cypress/e2e/silly.cy.tsx
  web-app/cypress/support/e2e.ts
  web-app/cypress/tsconfig.json
  web-app/index.html
  web-app/package-lock.json
  web-app/package.json
  web-app/postcss.config.cjs
  web-app/src/App.vue
  web-app/src/main.ts
  web-app/src/styles.scss
  web-app/src/vite-env.d.ts
  web-app/tailwind.config.cjs
  web-app/test/app.test.ts
  web-app/tsconfig.json
  web-app/tsconfig.node.json
  web-app/vite.config.ts
  web-app/vitest.config.ts
Labels: size/L

#93 Added husky dependency to package.json
  web-app/package-lock.json
  web-app/package.json
Labels: size/XS

#81 Identity integration
  web-api/src/Kerbero.Identity.Library/Modules/Authentication/Dtos/AuthenticatedDto.cs
  web-api/src/Kerbero.Identity.Library/Modules/Authentication/Dtos/LoginDto.cs
  web-api/src/Kerbero.Identity/Extensions/DependencyInjection/ServiceCollectionExtensions.cs
  web-api/src/Kerbero.Identity/Modules/Authentication/Controllers/AuthenticationController.cs
  web-api/src/Kerbero.Identity/Modules/Authentication/Models/AuthenticatedModel.cs
  web-api/src/Kerbero.Identity/Modules/Authentication/Services/AuthenticationService.cs
  web-api/src/Kerbero.Identity/Modules/Authentication/Services/IAuthenticationService.cs
  web-api/src/Kerbero.Infrastructure/Common/Context/ApplicationDbContext.cs
  web-api/src/Kerbero.Infrastructure/Kerbero.Infrastructure.csproj
  web-api/src/Kerbero.WebApi/Program.cs
  web-api/tests/Kerbero.Identity.Tests/Modules/Authentication/AuthenticationServiceTest.cs
Labels: size/L

#96 Logout identity library controller
  web-api/src/Kerbero.Identity/Modules/Authentication/Controllers/AuthenticationController.cs
  web-api/src/Kerbero.Identity/Modules/Authentication/Services/AuthenticationManager.cs
  web-api/src/Kerbero.Identity/Modules/Authentication/Services/AuthenticationService.cs
  web-api/src/Kerbero.Identity/Modules/Authentication/Services/IAuthenticationManager.cs
  web-api/src/Kerbero.Identity/Modules/Authentication/Services/IAuthenticationService.cs
  web-api/tests/Kerbero.Identity.Tests/Modules/Authentication/AuthenticationServiceTest.cs
Labels: size/M

#94 Registration confirm callback endpoint
  web-api/src/Kerbero.Identity/Modules/Users/Controllers/UsersController.cs
  web-api/src/Kerbero.Identity/Modules/Users/Services/IUserManager.cs
  web-api/src/Kerbero.Identity/Modules/Users/Services/IUserService.cs
  web-api/src/Kerbero.Identity/Modules/Users/Services/UserManager.cs
  web-api/src/Kerbero.Identity/Modules/Users/Services/UserService.cs
  web-api/tests/Kerbero.Identity.Tests/Modules/Users/Services/UserServiceTest.cs
Labels: size/L

#100 Check email confirmation during login
  web-api/src/Kerbero.Identity/Extensions/DependencyInjection/ServiceCollectionExtensions.cs
  web-api/src/Kerbero.Identity/Modules/Authentication/Services/AuthenticationService.cs
  web-api/tests/Kerbero.Identity.Tests/Modules/Authentication/AuthenticationServiceTest.cs
Labels: size/S

#84 Email sender with SendGrid client
  web-api/src/Kerbero.Identity/Common/KuamaIdentityConfiguration.cs
  web-api/src/Kerbero.Identity/Extensions/DependencyInjection/ServiceCollectionExtensions.cs
  web-api/src/Kerbero.Identity/Kerbero.Identity.csproj
  web-api/src/Kerbero.Identity/Modules/Email/Options/EmailSenderServiceOptions.cs
  web-api/src/Kerbero.Identity/Modules/Email/Services/EmailSenderService.cs
  web-api/src/Kerbero.Identity/Modules/Email/Services/IEmailSenderService.cs
  web-api/src/Kerbero.WebApi/Program.cs
  web-api/src/Kerbero.WebApi/appsettings.Development.json
  web-api/tests/Kerbero.Identity.Tests/Modules/Email/Services/EmailServiceTest.cs
Labels: size/L

#97 feat: mvp routing / auth store
  web-app/.gitignore
  web-app/cypress.config.ts
  web-app/cypress/e2e/silly.cy.tsx
  web-app/cypress/support/auth-routing.cy.ts
  web-app/cypress/support/commands.ts
  web-app/cypress/support/component-index.html
  web-app/cypress/support/component.ts
  web-app/cypress/support/cypress.d.ts
  web-app/cypress/support/e2e.ts
  web-app/cypress/tsconfig.json
  web-app/package-lock.json
  web-app/package.json
  web-app/src/App.vue
  web-app/src/auth/auth.store.ts
  web-app/src/auth/log-in.component.vue
  web-app/src/dashboard/dashboard.component.vue
  web-app/src/main.ts
  web-app/src/routing/router.ts
  web-app/src/routing/routing-guards.ts
  web-app/src/routing/routing-helpers.ts
  web-app/test/auth/auth.store.test.ts
Labels: size/L

#102 Using default dotnet identity cookie and fix double sign in
  web-api/src/Kerbero.Identity/Extensions/DependencyInjection/ServiceCollectionExtensions.cs
  web-api/src/Kerbero.Identity/Modules/Authentication/Controllers/AuthenticationController.cs
  web-api/src/Kerbero.Identity/Modules/Authentication/Services/AuthenticationService.cs
  web-api/src/Kerbero.Identity/Modules/Authentication/Services/IAuthenticationService.cs
  web-api/tests/Kerbero.Identity.Tests/Modules/Authentication/AuthenticationServiceTest.cs
Labels: size/L

#112 feat: split CI
  .github/workflows/webapi-integration.yml
  .github/workflows/webapp-integration.yml
Labels: size/M

#114 .env for app configuration and refactoring
  README.md
  web-api/.gitignore
  web-api/src/Kerbero.Identity/Common/KerberoIdentityConfiguration.cs
  web-api/src/Kerbero.Identity/Common/KerberoIdentityDbContext.cs
  web-api/src/Kerbero.Identity/Common/KerberoIdentityServicesOptions.cs
  web-api/src/Kerbero.Identity/Common/KuamaIdentityConfiguration.cs
  web-api/src/Kerbero.Infrastructure/Common/Options/NukiExternalOptions.cs
  web-api/src/Kerbero.Infrastructure/ConfigureService.cs
  web-api/src/Kerbero.Infrastructure/NukiActions/Repositories/NukiSmartLockExternalRepository.cs
  web-api/src/Kerbero.Infrastructure/NukiAuthentication/Repositories/NukiAccountExternalRepository.cs
  web-api/src/Kerbero.WebApi/.env-example
  web-api/src/Kerbero.WebApi/Kerbero.WebApi.csproj
  web-api/src/Kerbero.WebApi/Program.cs
  web-api/src/Kerbero.WebApi/appsettings.Development.json
  web-api/src/Kerbero.WebApi/appsettings.Test.json
  web-api/tests/Kerbero.Infrastructure.Tests/NukiActions/Repositories/NukiSmartLockExternalRepositoryTests.cs
  web-api/tests/Kerbero.Infrastructure.Tests/NukiAuthentication/Repositories/NukiAccountExternalRepositoryTests.cs
  web-api/tests/Kerbero.Integration.Tests/.env
  web-api/tests/Kerbero.Integration.Tests/KerberoWebApplicationFactory.cs
  web-api/tests/Kerbero.Integration.Tests/NukiAuthentication/NukiAuthenticationIntegrationTests.cs
Labels: size/L

#108 Ask for authorization for kerbero endpoints
  web-api/src/Kerbero.WebApi/Controllers/NukiAuthenticationController.cs
  web-api/src/Kerbero.WebApi/Controllers/NukiSmartLockController.cs
  web-api/tests/Kerbero.Integration.Tests/.env
  web-api/tests/Kerbero.Integration.Tests/IntegrationTestsUtils.cs
  web-api/tests/Kerbero.Integration.Tests/Kerbero.Integration.Tests.csproj
  web-api/tests/Kerbero.Integration.Tests/KerberoWebApplicationFactory.cs
  web-api/tests/Kerbero.Integration.Tests/NukiAuthentication/NukiAuthenticationIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLocks/NukiCloseSmartLockIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLocks/NukiCreateSmartLockIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLocks/NukiOpenSmartLockIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLocks/NukiSmartLocksListIntegrationTests.cs
Labels: size/L

#110 Signup endpoint, test and emailing refactor
  web-api/src/Kerbero.Identity/Extensions/DependencyInjection/ServiceCollectionExtensions.cs
  web-api/src/Kerbero.Identity/Modules/Email/Options/EmailSenderServiceOptions.cs
  web-api/src/Kerbero.Identity/Modules/Email/Services/EmailSenderService.cs
  web-api/src/Kerbero.Identity/Modules/Users/Controllers/UsersController.cs
  web-api/src/Kerbero.Identity/Modules/Users/Services/IUserManager.cs
  web-api/src/Kerbero.Identity/Modules/Users/Services/IUserService.cs
  web-api/src/Kerbero.Identity/Modules/Users/Services/UserManager.cs
  web-api/src/Kerbero.Identity/Modules/Users/Services/UserService.cs
  web-api/src/Kerbero.WebApi/Program.cs
  web-api/tests/Kerbero.Identity.Tests/Modules/Email/Services/EmailServiceTest.cs
  web-api/tests/Kerbero.Identity.Tests/Modules/Users/Services/UserServiceTest.cs
Labels: size/L

#115 Sign in api
  web-app/.env.example
  web-app/.env.test
  web-app/src/auth/api/auth.api.ts
  web-app/src/auth/api/auth.schemas.ts
  web-app/src/auth/components/log-in.component.vue
  web-app/src/auth/pages/authenticate.component.vue
  web-app/src/shared/http-client/http-client.ts
  web-app/test/auth/api/auth-sign-in.api.test.ts
  web-app/test/auth/api/auth-sign-up.api.test.ts
Labels: size/L

#117 fix: enforce eslint configuration
  .github/workflows/pr-integration.yml
  web-app/.eslintrc.cjs
  web-app/package-lock.json
  web-app/package.json
  web-app/src/auth/api/auth-actions.ts
  web-app/src/auth/api/auth.schemas.ts
  web-app/src/auth/pages/authenticate-page.component.vue
  web-app/src/auth/pages/authenticate.component.vue
  web-app/src/auth/stores/auth.store.ts
  web-app/src/dashboard/pages/dashboard-page.component.vue
  web-app/src/routing/router.ts
  web-app/test/app.test.ts
  web-app/test/auth/api/auth-sign-in.api.test.ts
  web-app/test/auth/api/auth-sign-up.api.test.ts
  web-app/test/auth/stores/auth.store.test.ts
Labels: size/M

#120 feat: add web-app coverage report
  .github/workflows/webapp-integration.yml
  web-app/package-lock.json
  web-app/vitest.config.ts
Labels: size/S

#122 Actions execution path
  .github/workflows/webapi-integration.yml
  .github/workflows/webapp-integration.yml
Labels: frontend, size/XS

#119 Email service .env config and integration
  web-api/src/Kerbero.Identity/Extensions/DependencyInjection/ServiceCollectionExtensions.cs
  web-api/src/Kerbero.Identity/Modules/Email/Options/EmailSenderServiceOptions.cs
  web-api/src/Kerbero.Identity/Modules/Email/Services/EmailSenderService.cs
  web-api/src/Kerbero.WebApi/Program.cs
  web-api/tests/Kerbero.Identity.Tests/Modules/Email/Services/EmailServiceTest.cs
Labels: size/M

#124 CreateKey interactor
  web-api/src/Kerbero.Domain/SmartLockKeys/Entities/SmartLockKey.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Errors/UnableToGenerateKeyError.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CreateSmartLockKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Managers/ISmartLockKeyGeneratorManager.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Mappers/SmartLockKeyMapper.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Models/PresentationRequests/CreateSmartLockKeyPresentationRequest.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Models/PresentationResponses/CreateSmartLockKeyPresentationResponse.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Repositories/ISmartLockKeyPersistentRepository.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/CreateSmartLockKeyInteractorTest.cs
Labels: size/L

#127 key generator manager
  web-api/src/Kerbero.Domain/SmartLockKeys/Errors/UnableToGenerateKeyError.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Interactors/CreateSmartLockKeyInteractor.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Managers/SmartLockKeyGeneratorManager.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/CreateSmartLockKeyInteractorTest.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Managers/SmartLockKeyGeneratorManagerTest.cs
Labels: size/M

#131 Moved NukiAccount creation before redirection to Nuki authentication
  web-api/src/Kerbero.Domain/NukiAuthentication/Entities/NukiAccount.cs
  web-api/src/Kerbero.Domain/NukiAuthentication/Interactors/CreateNukiAccountAndRedirectToNukiInteractor.cs
  web-api/src/Kerbero.Domain/NukiAuthentication/Interactors/ProvideNukiAuthRedirectUrlInteractor.cs
  web-api/src/Kerbero.Domain/NukiAuthentication/Interfaces/ICreateNukiAccountAndRedirectToNukiInteractor.cs
  web-api/src/Kerbero.Domain/NukiAuthentication/Models/ExternalRequests/NukiAccountBuildUriForCodeExternalRequest.cs
  web-api/src/Kerbero.Domain/NukiAuthentication/Models/ExternalResponses/NukiAccountBuildUriForCodeExternalResponse.cs
  web-api/src/Kerbero.Domain/NukiAuthentication/Models/PresentationRequests/CreateNukiAccountRedirectPresentationRequest.cs
  web-api/src/Kerbero.Domain/NukiAuthentication/Models/PresentationResponses/CreateNukiAccountAndRedirectPresentationResponse.cs
  web-api/src/Kerbero.Domain/NukiAuthentication/Models/PresentationResponses/NukiRedirectPresentationResponse.cs
  web-api/src/Kerbero.Domain/NukiAuthentication/Repositories/INukiAccountExternalRepository.cs
  web-api/src/Kerbero.Infrastructure/NukiAuthentication/Repositories/NukiAccountExternalRepository.cs
  web-api/src/Kerbero.WebApi/ConfigureService.cs
  web-api/src/Kerbero.WebApi/Controllers/NukiAuthenticationController.cs
  web-api/tests/Kerbero.Domain.Tests/NukiAuthentication/Interactors/CreateNukiAccountAndRedirectToNukiTest.cs
  web-api/tests/Kerbero.Domain.Tests/NukiAuthentication/Interactors/ProvideNukiAuthRedirectUrlTest.cs
  web-api/tests/Kerbero.Infrastructure.Tests/NukiAuthentication/Repositories/NukiAccountExternalRepositoryTests.cs
  web-api/tests/Kerbero.WebApi.Tests/Controllers/NukiAuthenticationControllerTest.cs
Labels: size/L

#140 .NET7 porting
  .github/workflows/webapi-integration.yml
  README.md
  web-api/README.md
  web-api/global.json
  web-api/src/Kerbero.Domain/Kerbero.Domain.csproj
  web-api/src/Kerbero.Identity.Library/Kerbero.Identity.Library.csproj
  web-api/src/Kerbero.Identity/Kerbero.Identity.csproj
  web-api/src/Kerbero.Infrastructure/Kerbero.Infrastructure.csproj
  web-api/src/Kerbero.WebApi/Kerbero.WebApi.csproj
  web-api/tests/Kerbero.Common.Data.Tests/Kerbero.Common.Data.Tests.csproj
  web-api/tests/Kerbero.Domain.Tests/Kerbero.Domain.Tests.csproj
  web-api/tests/Kerbero.Identity.Tests/Kerbero.Identity.Tests.csproj
  web-api/tests/Kerbero.Infrastructure.Tests/Kerbero.Infrastructure.Tests.csproj
  web-api/tests/Kerbero.Integration.Tests/Kerbero.Integration.Tests.csproj
  web-api/tests/Kerbero.WebApi.Tests/Kerbero.WebApi.Tests.csproj
Labels: size/L

#149 feat: add state and provider to smartlock
  web-api/src/Kerbero.Domain/SmartLocks/Dtos/SmartLockDto.cs
  web-api/src/Kerbero.Domain/SmartLocks/Dtos/SmartLockStateDto.cs
  web-api/src/Kerbero.Domain/SmartLocks/Interactors/GetSmartLocksInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Mappers/SmartLockMapper.cs
  web-api/src/Kerbero.Domain/SmartLocks/Models/NukiSmartLock.cs
  web-api/src/Kerbero.Domain/SmartLocks/Models/SmartLock.cs
  web-api/src/Kerbero.Domain/SmartLocks/Models/SmartLockState.cs
  web-api/src/Kerbero.Domain/SmartLocks/Models/SmartlockProvider.cs
  web-api/src/Kerbero.Infrastructure/NukiAuthentication/Entities/NukiCredentialEntity.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Mappers/SmartLockMapper.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Models/NukiDoorStateResponse.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Models/NukiSmartLockResponse.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Models/NukiSmartLockStateResponse.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Models/NukiSmartLockStateValueResponse.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Models/NukiSmartLockTypeResponse.cs
  web-api/src/Kerbero.WebApi/.env-example
  web-api/src/Kerbero.WebApi/Controllers/NukiCredentialsController.cs
  web-api/src/Kerbero.WebApi/Models/Requests/CreateNukiSmartLockCredentialRequest.cs
  web-api/tests/Kerbero.Integration.Tests/NukiAuthentication/NukiAuthenticationIntegrationTests.cs
Labels: size/L

#152 feat: ensure provided token is valid against nuki api
  web-api/src/Kerbero.Domain/NukiCredentials/Errors/NukiCredentialInvalidTokenError.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Interactors/CreateNukiCredentialInteractor.cs
  web-api/src/Kerbero.Domain/NukiCredentials/Repositories/INukiCredentialRepository.cs
  web-api/src/Kerbero.Infrastructure/NukiCredentials/Repositories/NukiCredentialRepository.cs
  web-api/src/Kerbero.WebApi/Utils/Extensions/ModelStateDictionaryExtension.cs
  web-api/tests/Kerbero.Domain.Tests/NukiCredentials/Interactors/CreateNukiCredentialInteractorTests.cs
  web-api/tests/Kerbero.Infrastructure.Tests/NukiCredentials/Repositories/NukiCredentialRepositoryTests.cs
  web-api/tests/Kerbero.Integration.Tests/NukiCredentials/NukiAuthenticationIntegrationTests.cs
Labels: size/L

#153 feat: get smartlock by id
  web-api/src/Kerbero.Domain/NukiActions/Errors/SmartLockNotFoundError.cs
  web-api/src/Kerbero.Domain/SmartLocks/Errors/SmartLockNotFoundError.cs
  web-api/src/Kerbero.Domain/SmartLocks/Repositories/INukiSmartLockRepository.cs
  web-api/src/Kerbero.Infrastructure/Common/Helpers/NukiSafeHttpCallHelper.cs
  web-api/src/Kerbero.Infrastructure/NukiActions/Repositories/NukiSmartLockPersistentRepository.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Repositories/NukiSmartLockRepository.cs
  web-api/src/Kerbero.WebApi/Utils/Extensions/ModelStateDictionaryExtension.cs
  web-api/tests/Kerbero.Domain.Tests/NukiActions/Interactors/CloseNukiSmartLockInteractorTest.cs
  web-api/tests/Kerbero.Domain.Tests/NukiActions/Interactors/OpenNukiSmartLockInteractorTests.cs
  web-api/tests/Kerbero.Infrastructure.Tests/NukiActions/Repositories/NukiSmartLockPersistentRepositoryTests.cs
  web-api/tests/Kerbero.Infrastructure.Tests/SmartLocks/Repositories/NukiSmartLockRepositoryTests.cs
Labels: size/L

#156 feat: bump dependencies version
  web-api/src/Kerbero.Identity.Library/Kerbero.Identity.Library.csproj
  web-api/src/Kerbero.Identity/Kerbero.Identity.csproj
  web-api/src/Kerbero.Infrastructure/Kerbero.Infrastructure.csproj
  web-api/src/Kerbero.WebApi/Kerbero.WebApi.csproj
  web-api/tests/Kerbero.Infrastructure.Tests/Kerbero.Infrastructure.Tests.csproj
  web-api/tests/Kerbero.Integration.Tests/Kerbero.Integration.Tests.csproj
Labels: size/S

#158 refactor(Identity): clean up warnings
  web-api/src/Kerbero.Identity.Library/Modules/Roles/Dtos/RoleReadDto.cs
  web-api/src/Kerbero.Identity/Modules/Roles/Mappings/RoleMappings.cs
  web-api/src/Kerbero.Identity/Modules/Users/Mappings/UserMappings.cs
  web-api/src/Kerbero.Identity/Modules/Users/Services/UserService.cs
  web-api/src/Kerbero.Identity/Modules/Users/Validators/PasswordValidator.cs
  web-api/tests/Kerbero.Identity.Tests/Modules/Roles/Services/RoleServiceTest.cs
  web-api/tests/Kerbero.Identity.Tests/Modules/Users/Services/UserServiceTest.cs
Labels: size/L

#157 refactor: drop NukiSmartLock
  web-api/src/Kerbero.Domain/NukiActions/Entities/NukiSmartLockEntity.cs
  web-api/src/Kerbero.Domain/NukiActions/Entities/NukiSmartLockStateEntity.cs
  web-api/src/Kerbero.Domain/NukiActions/Interactors/CloseNukiSmartLockInteractor.cs
  web-api/src/Kerbero.Domain/NukiActions/Interactors/CreateNukiSmartLockInteractor.cs
  web-api/src/Kerbero.Domain/NukiActions/Interactors/GetNukiSmartLocksInteractor.cs
  web-api/src/Kerbero.Domain/NukiActions/Interactors/OpenNukiSmartLockInteractor.cs
  web-api/src/Kerbero.Domain/NukiActions/Interfaces/ICloseNukiSmartLockInteractor.cs
  web-api/src/Kerbero.Domain/NukiActions/Interfaces/ICreateNukiSmartLockInteractor.cs
  web-api/src/Kerbero.Domain/NukiActions/Interfaces/IGetNukiSmartLocksInteractor.cs
  web-api/src/Kerbero.Domain/NukiActions/Interfaces/IOpenNukiSmartLockInteractor.cs
  web-api/src/Kerbero.Domain/NukiActions/Mappers/NukiSmartLockMapper.cs
  web-api/src/Kerbero.Domain/NukiActions/Repositories/INukiSmartLockPersistentRepository.cs
  web-api/src/Kerbero.Domain/SmartLockKeys/Entities/SmartLockKey.cs
  web-api/src/Kerbero.Identity/Common/KerberoIdentityConfiguration.cs
  web-api/src/Kerbero.Infrastructure/Common/Context/ApplicationDbContext.cs
  web-api/src/Kerbero.Infrastructure/Common/Interfaces/IApplicationDbContext.cs
  web-api/src/Kerbero.Infrastructure/ConfigureService.cs
  web-api/src/Kerbero.Infrastructure/NukiActions/Repositories/NukiSmartLockPersistentRepository.cs
  web-api/src/Kerbero.WebApi/ConfigureService.cs
  web-api/tests/Kerbero.Domain.Tests/NukiActions/Interactors/CloseNukiSmartLockInteractorTest.cs
  web-api/tests/Kerbero.Domain.Tests/NukiActions/Interactors/CreateNukiSmartLockInteractorTest.cs
  web-api/tests/Kerbero.Domain.Tests/NukiActions/Interactors/GetNukiSmartLocksListInteractorTest.cs
  web-api/tests/Kerbero.Domain.Tests/NukiActions/Interactors/OpenNukiSmartLockInteractorTests.cs
  web-api/tests/Kerbero.Domain.Tests/SmartLockKeys/Interactors/CreateSmartLockKeyInteractorTest.cs
  web-api/tests/Kerbero.Infrastructure.Tests/NukiActions/Repositories/NukiSmartLockPersistentRepositoryTests.cs
Labels: size/XXL

#155 feat: open smartlock (only nuki is supported)
  web-api/src/Kerbero.Domain/Common/Errors/UnsupportedSmartLockProviderError.cs
  web-api/src/Kerbero.Domain/Common/Models/SmartLockProviderModel.cs
  web-api/src/Kerbero.Domain/NukiActions/Models/PresentationRequest/OpenNukiSmartLockPresentationRequest.cs
  web-api/src/Kerbero.Domain/SmartLocks/Dtos/OpenSmartLockParams.cs
  web-api/src/Kerbero.Domain/SmartLocks/Dtos/SmartLockDto.cs
  web-api/src/Kerbero.Domain/SmartLocks/Interactors/OpenSmartLockInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Interfaces/IOpenSmartLockInteractor.cs
  web-api/src/Kerbero.Domain/SmartLocks/Mappers/SmartLockMapper.cs
  web-api/src/Kerbero.Domain/SmartLocks/Models/ESmartLockState.cs
  web-api/src/Kerbero.Domain/SmartLocks/Models/SmartLockModel.cs
  web-api/src/Kerbero.Domain/SmartLocks/Models/SmartlockProvider.cs
  web-api/src/Kerbero.Domain/SmartLocks/Repositories/INukiSmartLockRepository.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Mappers/SmartLockMapper.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Models/ENukiDoorStateResponse.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Models/ENukiSmartLockState.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Models/ENukiSmartLockType.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Models/NukiSmartLockResponse.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Models/NukiSmartLockStateResponse.cs
  web-api/src/Kerbero.Infrastructure/SmartLocks/Repositories/NukiSmartLockRepository.cs
  web-api/src/Kerbero.WebApi/ConfigureService.cs
  web-api/src/Kerbero.WebApi/Controllers/SmartLocksController.cs
  web-api/src/Kerbero.WebApi/Models/Requests/OpenNukiSmartLockRequest.cs
  web-api/src/Kerbero.WebApi/Models/Requests/OpenSmartLockRequest.cs
  web-api/tests/Kerbero.Infrastructure.Tests/SmartLocks/Repositories/NukiSmartLockRepositoryTests.cs
  web-api/tests/Kerbero.Integration.Tests/KerberoWebApplicationFactory.cs
  web-api/tests/Kerbero.Integration.Tests/NukiCredentials/NukiAuthenticationIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLocks/SmartLockIntegrationTests.cs
Labels: size/L

#159 feat: enabled enpoint slugify
  web-api/src/Kerbero.WebApi/Program.cs
  web-api/tests/Kerbero.Integration.Tests/NukiCredentials/NukiAuthenticationIntegrationTests.cs
  web-api/tests/Kerbero.Integration.Tests/SmartLocks/SmartLockIntegrationTests.cs
Labels: size/S
